################################
## Airflow Prometheus ClusterRole
#################################
{{- if .Values.global.rbacEnabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    tier: airflow-monitoring
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - "nodes"
      - "nodes/proxy"
      - "services"
      - "endpoints"
      - "pods"
    verbs:
      - "get"
      - "list"
      - "watch"
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - "get"
{{- end }}
