#################################
## Chart overrides
#################################

# Global overrides
global:
  baseDomain:
  tlsSecret:
  acme: false

nginx:
  loadBalancerIP:
  loadBalancerSourceRanges:
  - 0.0.0.0/0

# Airflow config overrides
airflow:
  env:
  secret:
