dependencies:
  - name: astronomer
    version: 0.2.1
    condition: global.modules.astronomer.enabled
  - name: airflow
    version: 0.2.1
    condition: global.modules.airflow.enabled
  - name: nginx
    version: 0.2.1
    condition: global.modules.nginx.enabled,global.baseDomain
