################################
## Airflow StatsD Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-statsd
  labels:
    tier: airflow-monitoring
    component: statsd
    tier: airflow-monitoring
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    tier: airflow-monitoring
    component: statsd
    release: {{ .Release.Name }}
  ports:
    - name: statsd-ingest
      protocol: UDP
      port: 9125
      targetPort: 9125
    - name: statsd-scrape
      protocol: TCP
      port: 9102
      targetPort: 9102
