################################
## NGINX Cluster Role Binding
#################################
{{- if .Values.global.rbacEnabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-nginx-ingress-controller
  labels:
    tier: nginx
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-nginx-ingress-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-nginx-ingress-controller
    namespace: {{ .Release.Namespace }}
{{- end }}
