################################
## Astronomer Registry Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    component: registry
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    component: registry
    tier: astronomer
    release: {{ .Release.Name }}
  ports:
    - name: registry-http
      protocol: TCP
      port: 5000
      targetPort: 5000
