################################
## Astronomer Commander Deployment
#################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ .Release.Name }}-commander
  labels:
    component: commander
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: commander
      tier: astronomer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: commander
        tier: astronomer
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-commander
      restartPolicy: Always
      securityContext:
        runAsUser: {{ .Values.uid }}
      containers:
        - name: {{ .Release.Name }}-commander
          image: {{ .Values.images.commander }}
          ports:
            - name: commander-http
              containerPort: 8880
            - name: commander-grpc
              containerPort: 50051
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8880
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8880
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: COMMANDER_HTTP_PORT
              value: "8880"
            - name: COMMANDER_GRPC_PORT
              value: "50051"
            - name: COMMANDER_KUBE_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: COMMANDER_HELM_REPO
              value: {{ .Values.global.helmRepo }}
            - name: HELM_HOST
              value: {{ .Values.global.helmHost }}
