################################
## Airflow Worker Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    tier: airflow
    component: worker
    tier: airflow-core
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    tier: airflow
    component: worker
    release: {{ .Release.Name }}
  ports:
    - name: worker-logs
      port: 8793
