################################
## Astronomer Houston Secrets
#################################

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-houston-jwt-passphrase
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  passphrase: {{ template "houston_jwt_passphrase" . }}
